language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

script: make test-static

# The default of --recursive chokes on the libgit2 tests
git:
  submodules: false

before_install:
  - git submodule update --init

matrix:
  allow_failures:
    - go: tip

branches:
  only:
  - master
  - /v\d+/
  - next
